### ISSUE TITLE
Merge in fixes from `lhnb`

### ISSUE THREAD

**Issue by deuill** [larrykollar/tines#1]
Good start with this project, `hnb` is fairly unique in its domain, even if a tad obscure.

It may be possible to merge in fixes from the [`lhnb` project](https://github.com/liskin/lhnb), which was also a continuation of `hnb` (though not as extensive a rehaul as `tines` seems to be) and contains various improvements and bugfixes.

**Comment by larrykollar** [comment]
Good to know—I wasn't aware that lhnb existed, or I'd have started with it. I'll definitely pull it and see what I can merge.
