### ISSUE TITLE
Missing and broken cli interface

### ISSUE THREAD

**Issue by peterjschroeder** [larrykollar/tines#11]
tines -e segfaults
tine -ui cli says unknown option

**Comment by larrykollar** [comment]
If you do `tines -e`, you need to include at least one CLI command. For example:

    tines -e 'today' 'go right' 'ls'

The old `-ui cli` option got replaced a while ago. The new option is `--ui=cli`

I'm going to close this issue and open a new one with just the first part.

**Comment by peterjschroeder** [comment]
It only shows one - in the command line options help. Two of them works tho, thank you.
