### ISSUE TITLE
create calendar is buggy

### ISSUE THREAD

**Issue by pscha** [larrykollar/tines#4]
When I create a calendar with the default configuration the calendar does not look as it is supposed to.
The month nodes are in the node above the year node and in reverse order. There is an empty node in there too.

after changing the tinesrc section about the calendar to the following:

            macro define pl_add_yr
                getquery "Year (4 digits)"
                add "$query Calendar"
                insert_below
                movenode down
                movenode right
                insert_cal 12 $query
                insert_cal 11 $query
                insert_cal 10 $query
                insert_cal 9 $query
                insert_cal 8 $query
                insert_cal 7 $query
                insert_cal 6 $query
                insert_cal 5 $query
                insert_cal 4 $query
                insert_cal 3 $query
                insert_cal 2 $query
                insert_cal 1 $query
            end

there is only the empty node left that is bugging me.

**Comment by larrykollar** [comment]
Fixed with the pull from pscha - thanks!

**Comment by larrykollar** [comment]
I've solved the leftover empty node problem. Use this:

			macro define pl_add_yr
				getquery "Year (4 digits)"
				add "$query Calendar"
				go bottom
				insert_below
				movenode right
				insert_cal 12 $query
				insert_cal 11 $query
				insert_cal 10 $query
				insert_cal 9 $query
				insert_cal 8 $query
				insert_cal 7 $query
				insert_cal 6 $query
				insert_cal 5 $query
				insert_cal 4 $query
				insert_cal 3 $query
				insert_cal 2 $query
				insert_cal 1 $query
				# needed to remove the blank node at top of cal
				go top
				remove
			end
