### ISSUE TITLE
Add encryption

### ISSUE THREAD

**Issue by peterjschroeder** [larrykollar/tines#9]
Encryption would be useful for storing passwords.

Someone wrote a patch, which is located here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=228454

**Comment by larrykollar** [comment]
I'm kind of on the fence with this one. There are keychain utilities, and entire encrypted filesystems,  available on all major operating systems (including Linux). Nevertheless, the patch *is* available. :)

It looks like there are several patches in that thread. Would you be willing to do a pull request, apply the right patch, and test it? I don't have GPG handy. I could test with openssl.

**Comment by peterjschroeder** [comment]
It can also use ccrypt. I'll give it a shot some time this weekend.

**Comment by larrykollar** [comment]
Thanks for trying!
